Numpy is a python library was created in 2005 by Travis
Numpy is used for with arrays .Numpy is short for "Numerical python" 50x faster than Traditional python lists.

NumPy was created by Travis Oliphant in 2005.

👨‍💻 Creator: Travis Oliphant
📅 Created: 2005
🐍 Name: NumPy = Numerical Python
🎯 Purpose: Fast numerical computing in Python, especially with arrays and mathematical operations.

NumPy evolved from earlier Python numerical libraries, particularly Numeric and numarray.

In [ ]:
# importing numpy library
import numpy as np
arr1 =np.array([1,2,3,4,])
print(arr1)

[1 2 3 4]


Differnt way to create numpy array

In [ ]:
# to create an array and we  can pass list ,tuple or any other array like object

In [ ]:
# Create 2D ARRAY

arr3 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr3)

[[1 2 3]
 [4 5 6]]


In [ ]:
# SEE the Diemnsion of sn array
print(arr3.ndim)

2


In [ ]:
# create  3D Array
arr4 = np.array([[[1, 2, 3],[4, 5, 6]] ,[ [7, 8, 9], [10, 11, 12] ]])

print(arr4.ndim)

3


In [ ]:
# Numpy array Indexing
arr5 = np.array([1,2,3,4,5])
print(arr5[2])
print(arr5[-1])

3
5


In [ ]:
print(arr5[-1:-5])
# negative index
print(arr5[-1])   # 5
print(arr5[-2])   # 4
print(arr5[-3])   # 3
print(arr5[0:3])
print(arr5[-3:-1])

[]
5
4
3
[1 2 3]
[3 4]


In [ ]:
# add an array element
arr = np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
# Access element on the first row ,second column
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('fifth row element: ',arr[1,4])

fifth row element:  10


In [ ]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
#Slice Element from begning to index 4
arr = np.array([4,5,6,7,6])
print(arr[-4:-1])

[5 6 7]


In [ ]:
#Slicing in 2d array
arr = np.array([[2,3,4,4,5],[6,7,8,9,10]])
print(arr[1,1:4])
print(arr[0:2,1:3])


[7 8 9]
[[3 4]
 [7 8]]


In [ ]:
##Data Types in numPY
# Numpy has some extra data types AND  refers to data types with someone Character
arr = np.array([1,2,3])
print(arr.dtype)

int64


In [ ]:
#Create a data types with differnt data types
arr = np.array([1,2,3],dtype ='i')
print(arr.dtype)

int32


In [ ]:
# for float
arr = np.array([1.1,1.2,3.4],dtype ='i')
print(arr.dtype)

int32


In [ ]:
#numpy Copy vs View
#COpy is a new array and view is just a view of the original array.
# make a copy the original array and the display bot arrays



In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(x)
print(arr)

[1 2 3 4 5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0]=42
print(x)
print(arr)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr.shape)

(5,)


In [ ]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr.reshape(5, 2))


TypeError: 'numpy.ndarray' object is not callable

In [ ]:
# Numpy is iterating
Iterating means going through one ny ones.

